BookingSite/BookingSite/Controllers/DailyReportController.cs
using BookingSite.Utils;
using BookingSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BookingSite.Controllers
{
    public class DailyReportController : Controller
    {
        //
        // GET: /DailyRepport/

        private const string ITEM_URI = ServerCommunicator.SERVER_URI + "concretebooking";

        public ActionResult Index()
        {
            var concreteBookings = ServerCommunicator.Get(ITEM_URI).DeserializeJson<IEnumerable<ConcreteBooking>>();

            var dates = new List<DateTime>();

            foreach (var cb in concreteBookings)
            {
                if (cb.Subject.Teacher.Username.Equals("kbr"))
                    dates.Add(cb.StartTime);
            }

            return List(concreteBookings, dates);   
        }

        public ActionResult List(IEnumerable<ConcreteBooking> concreteBookings, IEnumerable<DateTime> dates)
        {
            ViewBag.Bookings = concreteBookings.Where(cb => cb.Type != BookingType.Pending);
            ViewBag.PendingBookings = concreteBookings.Where(b => b.Type == BookingType.Pending);
            ViewBag.Dates = dates;

            return View("Index");
        }

        [HttpPost, ActionName("Filter")]
        public ActionResult GetDailyRepport()
        {
            var concreteBookings = ServerCommunicator.Get(ITEM_URI).DeserializeJson<ConcreteBooking[]>();
            var dates = new List<DateTime>();
            foreach (var cb in concreteBookings)
            {
                if (cb.Subject.Teacher.Username.Equals("kbr"))
                    dates.Add(cb.StartTime);
            }

            var date = DateTime.Parse(Request.Form["date"]);
            var currentBookings = concreteBookings.Where(cb => cb.StartTime == date);

            return List(currentBookings, dates);
        }

        public ActionResult Finish(int id)
        {
            ServerCommunicator.Put(
                ITEM_URI + "/" + id,
                (new Models.ConcreteBooking { Type = Models.BookingType.Finished }).SerializeToJsonObject());

            return Index();
        }

        public ActionResult Approve(int id)
        {
            ServerCommunicator.Put(
                ITEM_URI + "/" + id,
                new Models.ConcreteBooking { Type = Models.BookingType.Approved }.SerializeToJsonObject());

            return Index();
        }

        public ActionResult Reject(int id)
        {
            ServerCommunicator.Delete(ITEM_URI + "/" + id);
            return Index();
        }
    }
}

BookingSite/BookingSite/Views/DailyReport/Index.cshtml
@{
    ViewBag.PageId = "daily-report";
    ViewBag.Title = "Daglig Oversigt";
}
<div class="main-content">
    <h1>Dagsrapport</h1>

    <form method="post" action="@Url.Action("Filter", "DailyReport")"> 
            <div class="chose-date">
            <h3>Vælg dato</h3>
                <select name="date" id="date">
                @foreach (var date in ViewBag.Dates) {
                     <option>@date</option>
                }
                </select>
                <input type="submit" value = "Se rapport" />
           </div>
    </form>
    <div class="repport-table">
        <table>
        <tr>
            <th><input type="checkbox" onclick="checkAllBoxes()" class="master-checkbox"/></th>
            <th class="hidden">Id</th>
            <th>Fornavn</th>
            <th>Efternavn</th>
            <th>Fag</th>
            <th>Tid</th>
        </tr>
        @foreach (var e in ViewBag.Bookings)
        {
            <tr>
                <td><input type="checkbox" class="slave-checkbox"/></td>
                <td class ="hidden">@e.Id</td>
                <td>@e.Student.Name.FirstName</td>
                <td>@e.Student.Name.LastName</td>
                <td>@e.Subject.Name</td>
                <td>@e.StartTime</td> 
            </tr>
        }
            </table>
    </div>
    <div class="buttons">
        <button id="btn-finish">Marker som afsluttet</button>
    </div>
    <h3>Godkend bookinger</h3>
    <div class="approve-booking-table">
        <table>
        <tr>
            <th><input type="checkbox" onclick="checkAllBoxes()" class="master-checkbox"/></th>
            <th class="hidden">Id</th>
            <th>Fornavn</th>
            <th>Efternavn</th>
            <th>Fag</th>
            <th>Hold</th>
            <th>Tid</th>
            <th>Kommentar</th>
        </tr>
             @foreach (var e in ViewBag.PendingBookings)
        {
            <tr>
                <td><input type="checkbox" class="slave-checkbox"/></td>
                <td class ="hidden">@e.Id</td>
                <td>@e.Student.Name.FirstName</td>
                <td>@e.Student.Name.LastName</td>
                <td>@e.Subject.Name</td>
                <td>@e.Student.HomeRoomClass.Name</td>
                <td>@e.StartTime</td> 
                <td title="@e.Comment">@e.Comment</td> 
            </tr>
        }
        </table>
        <div class="buttons">
            <button id="btn-approve-booking">Godkend</button>
            <button id="btn-reject-booking">Afvis</button>
        </div>
    </div>
</div>